### ISSUE TITLE
Challenge / Response

### ISSUE THREAD

**Issue by aarondfrancis** [hansemannn/ti.bluetooth#14]
First of all, thanks for this awesome module. I've been able to scan and identify the bluetooth device I'm looking for. What I can't figure out, however, is how to authenticate to it. I was able to connect, but it immediately disconnected. I don't need to necessarily know the authentications codes, just how one would go about it. It connected and immediately disconnected.

```
[INFO]  connecting!
[INFO]  didConnectPeripheral
[INFO]  {
[INFO]      bubbles = 1;
[INFO]      cancelBubble = 0;
[INFO]      peripheral = "[object TiBluetoothPeripheral]";
[INFO]      source = "[object TiBluetoothCentralManager]";
[INFO]      type = didConnectPeripheral;
[INFO]  }
[INFO]  didDisconnectPeripheral
[INFO]  {
[INFO]      bubbles = 1;
[INFO]      cancelBubble = 0;
[INFO]      peripheral = "[object TiBluetoothPeripheral]";
[INFO]      source = "[object TiBluetoothCentralManager]";
[INFO]      type = didDisconnectPeripheral;
[INFO]  }
```

The device I'm trying to connect to is a Dexcom G5 Glucose Monitor. Much of the work has already been done, I'm just trying to do it in Titanium. https://github.com/LoopKit/xDripG5/blob/5cdf2d3e7783435072cffa997bd123a5b0c0c258/xDripG5/BluetoothServices.swift

**Comment by hansemannn** [comment]
Check this: https://lists.apple.com/archives/bluetooth-dev/2013/Apr/msg00151.html - Seems to happen in the native world as well.
