### ISSUE TITLE
Android parity

### ISSUE THREAD

**Issue by m1ga** [hansemannn/ti.bluetooth#2]
Add missing android parts

- [x] startScanWithServices
- [ ] didDiscoverServices
- [ ] didDiscoverCharacteristicsForService
- [ ] didUpdateValueForCharacteristic

**Comment by AppWerft** [comment]
Awesome work, i will look into tomorrow. Is it a generic BT-interface?

**Comment by hansemannn** [comment]
@AppWerft feel free to also contribute!

**Comment by hansemannn** [comment]
@m1ga Exposed `startScan` on iOS so we have good parity there. Also renamed `scanForPeripheralsWithServices` to `startScanWithServices` which takes an array of UUID's.

**Comment by m1ga** [comment]
👍 got it. I've changed my list

**Comment by AppWerft** [comment]
@m1ga  Do you see a sense to start scan with different modes (BALANCED, LOW_LATENCY, LOW_POWER,OPPORTUNISTIC) ?

**Comment by m1ga** [comment]
@AppWerft I didn't use BLE in any real-world project yet so I can't tell which scan mode is better but I think it's good to have a choice to set it. I've added `getScanMode()` and `setScanMode()` so you can set it yourself

**Comment by AppWerft** [comment]
OK, my thought was to use a method parameter …  I think serious about BT apps.

**Comment by hansemannn** [comment]
Having those in modes is better for scalable API's. Messing up the parameters should be avoided.

**Comment by AppWerft** [comment]
OK I have added setter and getter for it. Do you mean it is better to use parameters in methods to keep clean the class from new properties. What kind of pattern do you prefere?

**Comment by m1ga** [comment]
Like I've said in the previous comment: getter and setter is already implemented. I'll check your PR later and see what I can use

**Comment by AppWerft** [comment]
Ok, thsi was a parallel dev. anyway.

```java
@Kroll.constant
	public static final int SCAN_MODE_BALANCED = ScanSettings.SCAN_MODE_BALANCED;
	@Kroll.constant
	public static final int SCAN_MODE_LOW_LATENCY = ScanSettings.SCAN_MODE_LOW_LATENCY;
	@Kroll.constant
	public static final int SCAN_MODE_LOW_POWER = ScanSettings.SCAN_MODE_LOW_POWER;
	@Kroll.constant
	public static final int CAN_MODE_OPPORTUNISTIC = ScanSettings.SCAN_MODE_OPPORTUNISTIC;

	public final int DEFAULT_SCAN_MODE = SCAN_MODE_BALANCED;
	private int scanmode = DEFAULT_SCAN_MODE;


@Kroll.method
	public void setScanMode(int sm) {
		scanmode = sm;
	}

	@Kroll.method
	public int getScanMode() {
		return scanmode;
	}
````

**Comment by m1ga** [comment]
Started to work on `didDiscoverServices` and `didDiscoverCharacteristicsForService`. Commited the code already but still have to test it tomorrow.

**Comment by hansemannn** [comment]
Closing this ticket for now, since detaching both modules will speed-up each module's process. Still planning to normalize it as soon as we know what API's can be exposed cross-platform.
