### ISSUE TITLE
Expose BluetoothDeviceProxy on Android

### ISSUE THREAD

**Issue by AppWerft** [hansemannn/ti.bluetooth#4]
@miga Does we need a proxy for this? `onScanResult` could return a proxy instead of a simple dict. I think in next step we need methods on this Bluetoothdevice like `connectGatt` and ``writetoparcel etc.

**Comment by hansemannn** [comment]
@AppWerft wrong person linked

**Comment by AppWerft** [comment]
@hans OK, I start a proxy.

**Comment by hansemannn** [comment]
It's @m1ga, not @miga, that's what i meant  ;-)

**Comment by m1ga** [comment]
👍 Then I'll get notified. 
Adding more features is of course possible. At the moment I'll try to work on the parity issue first. Then we'll add more features (and make a roadmap or something)
What do you mean with `BluetoothDeviceProxy`? Don't find anything in the documentation or are you talking about exposing all BluetoothDevice settings

**Comment by AppWerft** [comment]
@m1ga I will expose all needed stuff. Look here: https://github.com/AppWerft/ti.bluetooth/tree/master/android/src/ti/bluetooth
Currently I cannot PR, because @hansemannn made a lot in iphone folder.

**Comment by m1ga** [comment]
Again: just add the necessary files with `git add file.a file.b ...` and you can create a PR just for your files and not for everything. Or if you are using a GUI like SourceTree you can just select the files you want to add in your PR

**Comment by hansemannn** [comment]
See #6, just create a new branch based on the latest master, copy the Android into there and commit it. Easy as that.

**Comment by AppWerft** [comment]
@m1ga I have only added my java files. I have in Studio in commit window only the java files

@hansemannn I will try, I think the best solution.

**Comment by AppWerft** [comment]
and how "create a new branch based on the latest master"? Sorry.

**Comment by m1ga** [comment]
either update your current fork:
https://github.com/hansemannn/ti.bluetooth/pull/3#issuecomment-269133799
or like this: http://stackoverflow.com/a/7244456/5193915
or create a new fork and start from there
